### ISSUE TITLE
Problem with Python dependencies

### ISSUE THREAD

**Issue by jsdodge** [unibe-icelab/thz-image-explorer#13]
I obtain the following error when I run `pip install -r requirements.txt`, as specified in the documentation.

```console
      In file included from src/c_api.c:15:
      In file included from src/c_api.h:22:
      src/geos.h:15:10: fatal error: 'geos_c.h' file not found
         15 | #include <geos_c.h>
            |          ^~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for shapely
Successfully built numpy
Failed to build shapely
error: failed-wheel-build-for-install
```

**Comment by hacknus** [comment]
Ah, thanks, I see, this is an issue because I specified an older version of shapely that is not compatible with Python 3.13. I fixed this now. For me it now works with Python 3.13!
